### POST Request
POST http://localhost:3000/employee-api/employees
Content-Type: application/json

{
    "name" : "Samanvi",
    "email" : "samanvi@gmail.com",
    "mobile" : 34687890,
    "designation" : "Hyd",
    "companyName" : "Amazon"
}

### GET Request

GET http://localhost:3000/employee-api/employees

### PUT Request

PUT http://localhost:3000/employee-api/employees/69ca297a0b1deb9266096be8
Content-Type: application/json

{
    "name" : "Sanjana",
    "email" : "sanjana@gmail.com",
    "mobile" : 34687890,
    "designation" : "Hyd",
    "companyName" : "Start-up"
}

### DELETE Request

DELETE http://localhost:3000/employee-api/employees/69ca297a0b1deb9266096be8


